### ISSUE TITLE
[after-sales service :=)] questions about settings

### ISSUE THREAD

**Issue by ghost** [claustromaniac/poop#10]
Hi,

Running POOP 1.1.0 flawlessly on Firefox 64.0 (x64) / Windows 7 (x64).

I have two questions  in mind regarding the options, thanks for any clarification.

- Modes : Is the _aggressive mode_ the same as the _relaxed mode_ with **all** _Type filters_ checked?
- Other : What exactly is performed by Spoof cross-origin?

At this time I've set,

```
Global Mode = aggressive
Overrides = 0: www.google.com/maps/*
Type filters = default (font & stylesheet)
Exclusions = www.youtube.com *.googlevideo.com
```

If a site doesn't render correctly (the culprit being POOP) I first set the mode for the domain to relaxed and if the issue remains I whitelist the domain. I have in mind as well, depending on the domain, if I should rather fine-tune by considering Overrides or Exclusions.

For the fun of the _Guinness Books of Records syndrome_ I've noticed two sites which trigger POOP's counter as a rocket hits the skies : [Mappy Maps](https://fr.mappy.com/) and [CNN USA on Livenewson](https://www.livenewson.com/american/cnn-news-usa.html) : wow!

Thanks for this great contribution to a more civilized Web :=)

**Comment by crssi** [comment]
@claustromaniac 's quote:

> Aggressive mode is basically the same as relaxed mode, except it doesn't care if requests include cookies or the query section of the URL. In other words, it removes origins from all GET requests, simple as that.

Spoof cross-origin is altering `Referer` header to the destination domain, when `Origin` was also altered in the same header. Basically very similar to Smart Referer extension (SR) or uMatrix (uM) spoof referer, but as said only when `Origin` header is altered.
This setting is meant for the users who does not alter `Referer` by other extensions already... like SR or uM.

My settings are:
```
Global mode: relaxed
Overrides: none
Type filters: font, stylesheet, xmlhttprequest (XHR)
Exclusions:
  Exclude root domain matches: Checked
  List: www.youtube.com *.googlevideo.com
Spoof cross-origin: Checked
```
Let me shortly explain my choices:
If you allow only 1st party cookies, then I don't see a reason to go into aggressive mode.
`Exclude root domain matches` should be checked since it really doesn't matter (tracking wise) of Origin presence in requests to 1st party, but for sure it can lead to breakages (if left unchecked).
When `Exclude root domain matches` is checked, you can allow yourself to check the `xmlhttprequest (XHR)`, this way you will get rid of almost 100% of leakages (talking about GET requests and what I have observed).
XHR POST request must be dealt with good uBlock Origin (uBO) (and/or uM) filter (asset) sources. In my GitHub Firefox repository there are two zip's with settings I am using, one for uBO and one for uM.

I am fully open for a debate, criticism, questions.

Cheers

**Comment by ghost** [comment]
OK, @crssi that's interesting. I understand your settings' correlation to the user's choices regarding the browser (cookies permission). I have as well 3rd-party coolies blocked (as well as a uBO 'hard-mode') so I'll follow your settings given I understand your explanation.

I've just modified my POOP settings according to yours and Google Maps satellite view doesn't require anymore the `0: www.google.com/maps/*` override because of `Exclude root domain matches: Checked` as I understand it.

That makes it far more clear to me. Thanks :+1:

**Comment by crssi** [comment]
No problem mate. Glad to help. But, if you find any doubt or breakage, please, let me know... it will help me to improve solution and my knowledge.
Also, it would be interesting to somehow collect XHR POST requests (of course with privacy sensitive information stripped out) as a base to build privacy potection uBO filter list. The problem is that no one would share that data.

Cheers

**Comment by claustromaniac** [comment]
@crssi already explained this (thanks!), but I will add the following:

> Is the aggressive mode the same as the relaxed mode with all Type filters checked?

It should be the same in practice but, technically, the difference is that there exist [a few other resource types][types] that are not listed in the **Type filters** section (like `speculative` and such). I didn't add checkboxes for those because it seemed excessive. In fact, I think many would already consider the number of options in there a bit excessive.

By the way, the relaxed mode is currently taking more things into account than just the cookies and URL parameters. I'll try to update the documentation to elaborate on that.

[types]: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/ResourceType

**Comment by ghost** [comment]
Aggressive mode greater than FULL relaxed mode (few more resource types) : OK

> By the way, the relaxed mode is currently taking more things into account than just the cookies and URL parameters. I'll try to update the documentation to elaborate on that.

I did notice some sites showing more altered requests with aggressive mode. In doubt I reverted Global Mode to aggressive.

I keep all the other settings explained by @crssi : 

```
Type filters: font, stylesheet (default) **PLUS** xmlhttprequest (XHR)
Exclusions:
  Exclude root domain matches: **Checked**
  List: www.youtube.com *.googlevideo.com (that, I found out quickly myself!)
Spoof cross-origin: **Checked**
```

Thanks @claustromaniac 

Once you get used to it and for a newbie as myself start conceptualizing accordingly, things get easier :=)

**Comment by crssi** [comment]
Cool... let us know, please, if you have some breakages (and what the case is... URL) with aggressive mode.

Cheers

**Comment by ghost** [comment]
I guess the idea is always that tougher is the filtering (fine tuning) more a user has to intervene.

As I understand it @claustromaniac included several settings because there isn't one which would be the best : set it and forget it, more or less but rather less than more (_relax_, Max!) or set it and sleep/relax with an opened (_aggressive_!) eye.

But what I've learned from @crssi comment above is that one's choice regarding POOP's settings must take into consideration the browser's settings as well : likely you won't set POOP the same way with Firefox out of the box than with it heavily protected already by other means (settings, other extensions).

This makes the scheme a car race scenario where the pilot and engineers have to optimize not only settings but settings within their interactions. Theory then practice. I'll drive as we all do and report any conflict but again it's obvious that once the extension does it job (and POOP does it indeed) the implications are no longer flaws or issues but the driver's confrontation to his choices.

Those were a 24th of December deep thoughts, now shifting towards Santa : Merry Christmas to all :=)

**Comment by claustromaniac** [comment]
Quoting myself:

> the relaxed mode is currently taking more things into account than just the cookies and URL parameters. I'll try to update the documentation to elaborate on that.

[Done](https://claustromaniac.github.io/poop/#-how-exactly-does-the-relaxed-mode-work)

> As I understand it @claustromaniac included several settings because there isn't one which would be the best : set it and forget it, more or less but rather less than more (relax, Max!) or set it and sleep/relax with an opened (aggressive!) eye.

Indeed. There is no one-size-fits-all solution because there are many factors to take into account, and different users will find different approaches more comfortable than others, and will have different tolerance levels as well. To be honest, it took me a white to admit it because it meant more work for me :sweat_smile:

Thanks again for your feedback Stan. Merry Xmas and happy new year to you both!

### :heart::tada::beers:

**Comment by bitpixl** [comment]
Hi claustromaniac, I just stumbled and stepped into this huge pile of poop while browsing ghacks and this seems like another must have addon.

I do have some questions, so I hope you don't mind me opening this topic again.
My questions are regarding using poop with other addons and their settings.

- Can Poop basically replace Smart Referer?

- Im also using Neat URL with these extra added URL request types:
font, image, imageset, media, object, object_subrequest, script, stylesheet, sub_frame, websocket, xbl, xml_dtd, xmlhttprequest, xslt, other

Am I right in thinking that Poop makes this specific part of Neat URL redundant?

Thanks and happy new year!

**Comment by bitpixl** [comment]
So I did some testing to see if I can replace Smart Referer with Poop:

I'm using relaxed mode with xmlhttprequest (XHR) checked to enable aggresive mode.
Exlude root domain matches is checked.
Spoof cross-origin Referer is checked.

I load one of my homevideo's on photos.google.com and I get the loading screen which ends up eventually in an error screen.

I uncheck xmlhttprequest (XHR) and the video does load.

Now when using Smart Referer I need to add the exception "photos.google.com youtube.googleapis.com" to get the video's working, but adding this line to the exclude request part in Poop doesn't seem to work.

Any ideas how I can get it to work while still having aggressive enabled for xmlhttprequest (XHR)?
Or at least what steps to take to solve my issue? I've tried looking in the console, but there's alot going on in there and I don't know what to focus on.

**Comment by claustromaniac** [comment]
> Can Poop basically replace Smart Referer?

The answer to this is question implied in what @crssi explained [above](https://github.com/claustromaniac/poop/issues/10#issuecomment-449572967). 

Basically, the answer is **no**. The scope is different. This extension is not meant to deal with `Referer` headers, it is only meant to deal with `Origin` headers. It tampers with the `Referer` header **only** in the requests that will have their `Origin` header stripped from. It outright ignores `Referer` headers in all the other requests (the ones that it skips).

> Am I right in thinking that Poop makes this specific part of Neat URL redundant?

No, Neat URL removes URL parameters as far I know. POOP doesn't touch the URL in any way.

> Now when using Smart Referer I need to add the exception "photos.google.com youtube.googleapis.com" to get the video's working, but adding this line to the exclude request part in Poop doesn't seem to work.

I don't know since I don't use that service and I can't check right know, but the only way I can explain what you describe is that POOP is causing some other request(s) in that site to fail. POOP and Smart Referer do different things, after all. You can either:

1. easy solution: override the *mode* for that site (from the popup) to *whitelisted*
2. harder solution: look for the culprit in the console (CORS errors are thrown in yellow *warnings*) and create new exclusions for the requests that are failing, one at a time (reloading the page to test changes every time), until the video loads without a hassle.

An alternative way to go about this (easier than `#2` IMO) is to leave the `Type filters` section at default (stylesheet + font checked) and use the **global** *aggressive* mode, and override the mode for that site (from the popup) to *relaxed*.

**Comment by crssi** [comment]
@bitpixl 

Add:
```
*.googleapis.com *.googleusercontent.com
*.googleapis.com *.googlevideo.com
*.googleapis.com *.google.com
```

Please, report back the results.
Next time, please, open a new issue.

Thank you for report and cheers

**Comment by crssi** [comment]
Actually there is no point to alter `Origin` in any requests from EvilCorp to EvilCorp (raising FP)... so:
```
*.youtube.com *.googlevideo.com
*.youtube.com *.gstatic.com
*.youtube.com *.ytimg.com
*.google*.* *.google*.*
*.google*.* *.gstatic.com
```

@claustromaniac What is your opinion?

**Comment by claustromaniac** [comment]
Sure, that's likely for the best :+1: It would probably be a good idea to use the same approach with other companies like some CDNs and such.

**Comment by bitpixl** [comment]
@crssi it works now after adding the exclusions :+1: 
using relaxed mode with aggressive on font / stylesheet / xmlhttprequest (XHR).

Fingerprint wise, I guess using this addon makes us quite unique atm? (based on installed addons in firefox) ;)

**Comment by claustromaniac** [comment]
> Fingerprint wise, I guess using this addon makes us quite unique atm? (based on installed addons in firefox) ;)

That really depends on what the server is expecting. It's not unlike visiting the URL for a resource directly (because there are no `Origin` headers in those requests either). Also, it is arguably better than leaking the sites you browse to 3rd parties, and there is a lot more data to use for fingerprinting anyway.

**Comment by crssi** [comment]
I would fully agree with @claustromaniac.

OT: I have also script checked.

**Comment by bitpixl** [comment]
thank you for your input and have a great new years, feel free to close this topic again.

**Comment by crssi** [comment]
I had over complicated post at https://github.com/claustromaniac/poop/issues/10#issuecomment-450574209.

When you are already at EvilCorp as source, there is no need to alter any destinations. All destinations are anyway "tracked" to the same EvilCorp.

So, simplified would be:
```
*.youtube.com *
*.google*.* *
```

Agree?

Cheers

**Comment by claustromaniac** [comment]
Umm, I don't know. That's likely fine, but there might be special cases we're not aware of.
