### ISSUE TITLE
[PooP 1.2.1] Agresive and relaxed seems same

### ISSUE THREAD

**Issue by crssi** [claustromaniac/poop#11]
Something isn't right or I am wrong, but I can't see the difference between relaxed and aggressive mode.

Visit for example `https://io9.gizmodo.com/the-nerds-watch-the-best-sci-fi-and-fantasy-streaming-1831179417` and observe requests with `Origin` header in relaxed and in aggressive mode.

I don't see a difference. :cry: 

Cheers

**Comment by crssi** [comment]
^^It's two `Options` requests to `api.vmh.univision.com` that caught my attention.
Maybe its too late and I don't see "something". :smile:

**Comment by claustromaniac** [comment]
[These are the changes in `1.2.1`](https://github.com/claustromaniac/poop/compare/2330c74...9d53355)

If it's only `OPTIONS` requests where you don't see a difference, then that is expected, because this extension only touches `GET` requests (regardless of the mode) :stuck_out_tongue:

Thanks for testing it so promptly, though. :heart:

EDIT: Kinda late for me too because it seems I didn't get the joke in your last comment. Feeling all Sheldon Cooper now. :man_facepalming:

**Comment by crssi** [comment]
Doh... it was too late back then, my eyes were closing up, my brains was telling me something is odd but couldn't "decode" what. :smile: 

OK... if you take ^^upper URL as an example.
We have two `OPTIONS` requests with leaking `Origin`header, for two `GET` request where `Origin` was neutralized by PooP.
Those two `OPTIONS` requests have header `Access-Control-Request-Method: GET` <- pay attention to GET part.
My head is still fuzzy, but something is telling me that `OPTIONS` request where ACRM = GET, should also be altered somehow.

Reopen if applicable. ;)

Cheers
