### ISSUE TITLE
Exclusions section list naming and default value

### ISSUE THREAD

**Issue by crssi** [claustromaniac/poop#15]
Maybe the list box in exclusions section should be named `Whitelist`?
I don't see any reason not to include `www.youtube.com *.googlevideo.com` as default in there.

**Comment by claustromaniac** [comment]
> Maybe the list box in exclusions section should be named `Whitelist`?

I already used the word *whitelist* in the **Overrides** section (`0` = whitelisted). When you think about it, disabling the extension for a specific **site** is akin to whitelisting a site in uBO, since the extension just skips all requests made from that tab. Seems intuitive to me.

I wanted a different word for the feature you're referring to, and I concluded that *exclusions* fits the bill perfectly, and leaves no room for confusion. It should be clear that those requests are being left out (not being touched), but we both are foreign english speakers, so it would be nice to get some feedback from the natives.

> I don't see any reason not to include `www.youtube.com *.googlevideo.com` as default in there.

Youtube videos shouldn't break with the extension's defaults anyway, since it defaults to relaxed + fonts + css. I didn't see any reason to add any default exclusions taking that into account, so I opted for *suggesting* that rule in the placeholder text in the `<textarea>` (when it's empty), as an example. Also, I prefer not to add default exclusions in general because it is more shit to maintain.
