### ISSUE TITLE
?: POOP & TC

### ISSUE THREAD

**Issue by atomGit** [claustromaniac/poop#18]
assuming one doesn't dump different domains in the same container and then surf all over using that container, is there still an advantage to using POOP with TC (in auto-mode)?

**Comment by claustromaniac** [comment]
Containers are good for two things:
1. Isolating persistent data (cookies, cache, etc)
2. Clearing persistent data.

Isolation has its limits because all servers can still see your IP and your overall fingerprint and correlate your requests.

POOP helps prevent the browser from disclosing (via CORS) which sites you are browsing to third parties. It's a different scope.

So, the answer to your question is **Yes**. The only alternative to using POOP (and still prevent exposing the sites you browse to third parties) is to block all third-party requests. Or at least, I can't think of any other alternatives right now.

**Comment by atomGit** [comment]
oh goodie! i get to keep poop!

you're answer is what i suspected but i wanted to be sure cause my head isn't inside all this stuff

thanks for the detailed comment - appreciated

**Comment by claustromaniac** [comment]
You're welcome. 

This question made me realize that the documentation is lacking in the user-friendliness department because it never states in clear bold letters what **exactly** it is addressing. I mean, the info is there, but it is mostly implied. I should improve that.
