### ISSUE TITLE
remove referrer header?

### ISSUE THREAD

**Issue by atomGit** [claustromaniac/poop#5]
re:

> You should remove Referer headers too when the origin & target hostnames don't match, which this extension doesn't do on its own. You can use other extensions for that, or simply set network.http.referer.XOriginPolicy to 2 in about:config.

wadif i set it to 0 and enable the spoof 3rd party referrer option in uMatrix? my understanding is that this should be fine ... i think?

**Comment by claustromaniac** [comment]
Yes, that would be fine. This extension will spoof `Referer` headers in cross-origin requests by default, though. I already implemented it and will do another pre-release in a short while. Once I make the actual release on AMO I will remove that warning from the readme.

**Comment by rarecaller** [comment]
Could you bring more clarity to the description of option "Spoof cross-origin Referer"?

First of all, how exactly this spoofing works? Usually, spoofing means replacing actual data with some fake data. But in such a case fake header is still a header, and fake `Referer` still looks untypical alongside the removed `Origin` header, continuing to make me unique. So what is spoofing in this particular case?

Second, could you compare the effect of this option with the effect of `network.http.referer.XOriginPolicy` set to "1" and "2"? (ghacks-user.js recommends "1")This about:config preference allow to completely disable `Referer` sending across origins by limiting it with first-party domain. Could it be the better approach, or POOP's built-in spoofing have some advantages?

**Comment by crssi** [comment]
When the Origin is spoofed to match the target (not revealing your browsing site I mean), then the Referer value is also spoofed to be a match with spoofed Origin value. This way will not reveal You as unique.
If you are using other (3rd party) Referer spoofing solutions, like ghacks-user.js or Smart Referer extensions, then you can uncheck this setting, since your 3rd party solution would need to cover that.
This option is a precaution to cases where user does not already use some 3rd party Referer solution or appropriate preferences in FF.

I hope I answered your question in a understandable way.

Cheers

**Comment by rarecaller** [comment]
Smart Referer and ghacks-user.js are NOT spoofing solutions, because they completely remove Referer header from cross-origin requests. Like I said, spoofing and removing are different things, so I see some kind of misunderstanding here.
For example, if I want to get rid of canvas fingerprinting, I have a choice of removing it by disabling the Canvas API in my browser, or installing Canvas Blocker add-on that will generate a random values of it. Result will be different.

**Comment by crssi** [comment]
For sure you are right and I used bad "wording" (I am not english native speaker)... but, I will guess, you already know what I was trying to say?

**Comment by claustromaniac** [comment]
@rarecaller, Sorry I didn't see this question until just now. 

As crssi said, that option is only meant to cover users that are not already dealing with referer headers via other means, so as to prevent this extension to *cause* them to look more unique than they did fingerprinting-wise. 

The behavior of that feature is the same as Firefox's `network.http.referer.spoofSource` pref (see 49bca5e). The reason the extension spoofs instead of removing that header is simply to avoid breakage, and it only affects requests that get their `Origin` headers stripped from, as dictated by your personal settings. Also, it wouldn't make as much sense to merely *trim* the `Referer` for those requests when the goal of the extension is to avoid disclosing the `Origin` (since they can match).

I hope that makes sense.
